--트리거
--테이블에 부착해서 INSERT,UPDATE,DELETE 작업이 수행될 때
--'특정코드'가 실행되도록함
--종류 (INSERT,UPDATE,DELETE) 이전 : BEFORE 트리거
--                            이후 : AFTER 트리거
--사용하는 KEYWORD 참조 전 열값 : OLD
--                    후 열값 : NEW
SET SERVEROUTPUT ON;
CREATE TABLE TBL_TEST (
    ID VARCHAR2(30),
    TEXT VARCHAR2(30)
);

-- 트리거 생성
CREATE OR REPLACE TRIGGER TBL_TEST_TRG
    AFTER UPDATE OR INSERT OR DELETE
    ON TBL_TEST
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('트리거 동작');
END;
--
INSERT INTO TBL_TEST VALUES('AAA123','HELLO');
UPDATE TBL_TEST SET TEXT = 'BYE' WHERE ID = 'AAA123';
DELETE FROM TBL_TEST WHERE ID = 'AAA123';
----------------
--AFTER TRIGGER
--:OLD = 참조전 값(I:입력전자료,U: 변경전자료, D: 삭제전자료)

--원본테이블과 백업테이블 생성
CREATE TABLE TBL_USER(
    ID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20),
    ADDRESS VARCHAR2(30)
);

CREATE TABLE TBL_USER_BACKUP(
    ID VARCHAR2(20),
    NAME VARCHAR2(20),
    ADDRESS VARCHAR2(30),
    UPDATEDATE DATE DEFAULT SYSDATE,
    M_TYPE CHAR(10), --변경타입
    M_USER VARCHAR2(20) --변경한 사용자
);
--TBL_USER에 업데이트 OR 딜리트가 일어나면, 기존데이터를 백업할거야
CREATE OR REPLACE TRIGGER TBL_USER_BACKUP_TRG
    AFTER UPDATE OR DELETE
    ON TBL_USER
    FOR EACH ROW
DECLARE
    V VARCHAR2(10); -- 지역변수
BEGIN
    IF UPDATING THEN --UPDATE가 일어나면 TRUE
        V := '수정';
    ELSIF DELETING THEN --DELETE가 일어나면 TRUE
        V := '삭제';
    END IF;
    
    -- 변경되기전 자료
    INSERT INTO TBL_USER_BACKUP VALUES(:OLD.ID, :OLD.NAME, :OLD.ADDRESS,SYSDATE,V,USER());
END;

INSERT INTO TBL_USER VALUES('AAA', 'AAA', 'AAA');
INSERT INTO TBL_USER VALUES('BBB', 'BBB', 'BBB');

UPDATE TBL_USER SET NAME = 'NEWAAA' WHERE ID = 'AAA';  --트리거 동작
DELETE FROM TBL_USER WHERE ID = 'BBB';  --트리거 동작

SELECT * FROM TBL_USER_BACKUP;

-- BEFORE 트리거
-- :NEW 는 입력하기 전 자료, 참조 후 값,(I:입력할 자료, U: 수정할자료)
CREATE OR REPLACE TRIGGER TBL_USER_MAKING_TRG
    BEFORE INSERT
    ON TBL_USER
    FOR EACH ROW
BEGIN 
    --인서트가 되기전에 데이터를 변경
    :NEW.NAME := SUBSTR(:NEW.NAME,1,1) || '**';
END;

INSERT INTO TBL_USER VALUES ('CCC','홍길동','서울시');
INSERT INTO TBL_USER VALUES ('DDD','이순신','서울시');

SELECT * FROM TBL_USER;